#!/usr/bin/env bash

# 배포 도중 일부 명령만 실패한 상태로 다음 단계가 실행되지 않도록 엄격하게 처리한다.
set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly COMPOSE_FILE="${PROJECT_ROOT}/compose.yml"
readonly ENV_FILE="${PROJECT_ROOT}/.env"
readonly RUNTIME_DIR="${PROJECT_ROOT}/runtime"
readonly DEPLOYMENT_ENV_FILE="${RUNTIME_DIR}/deployment.env"
readonly NGINX_RUNTIME_DIR="${RUNTIME_DIR}/nginx"
readonly ACTIVE_BACKEND_FILE="${NGINX_RUNTIME_DIR}/active-backend.conf"
readonly DEPLOYMENT_LOCK_FILE="${RUNTIME_DIR}/deploy.lock"

temporary_state_file=""
temporary_upstream_file=""

print_usage() {
  cat <<'EOF'
Usage: ./scripts/deploy-backend.sh <backend-image-tag>

Example:
  ./scripts/deploy-backend.sh 0123456789abcdef0123456789abcdef01234567
EOF
}

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

warn() {
  printf 'Warning: %s\n' "$1" >&2
}

cleanup_temporary_files() {
  if [[ -n "${temporary_state_file}" && -e "${temporary_state_file}" ]]; then
    rm -f -- "${temporary_state_file}"
  fi

  if [[ -n "${temporary_upstream_file}" && -e "${temporary_upstream_file}" ]]; then
    rm -f -- "${temporary_upstream_file}"
  fi
}

trap cleanup_temporary_files EXIT

if (( $# != 1 )); then
  print_usage
  exit 1
fi

readonly new_backend_tag="$1"

# Docker tag에 사용할 수 없는 문자나 셸 명령 문자가 전달되는 것을 차단한다.
if [[ ! "${new_backend_tag}" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]]; then
  fail "backend-image-tag is not a valid Docker tag."
fi

[[ -f "${COMPOSE_FILE}" ]] || fail "compose.yml was not found at ${COMPOSE_FILE}."
[[ -f "${ENV_FILE}" ]] || fail ".env was not found. Copy .env.example and enter the real EC2 values first."

command -v docker >/dev/null 2>&1 || fail "docker command was not found."
command -v flock >/dev/null 2>&1 || fail "flock command was not found."
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin was not found."

mkdir -p -- "${NGINX_RUNTIME_DIR}"

# 같은 EC2에서 두 배포가 동시에 A/B 상태를 변경하지 못하도록 잠금을 획득한다.
exec 9>"${DEPLOYMENT_LOCK_FILE}"
flock -n 9 || fail "another backend deployment is already running."

compose() {
  docker compose \
    --project-directory "${PROJECT_ROOT}" \
    --file "${COMPOSE_FILE}" \
    --env-file "${ENV_FILE}" \
    --env-file "${DEPLOYMENT_ENV_FILE}" \
    "$@"
}

is_valid_tag() {
  [[ "$1" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]]
}

write_deployment_state() {
  local active_slot="$1"
  local backend_a_tag="$2"
  local backend_b_tag="$3"
  local deployment_initialized="$4"

  umask 077
  temporary_state_file="$(mktemp "${RUNTIME_DIR}/.deployment.env.XXXXXX")"

  printf '# Generated by deploy-backend.sh. Do not commit this file.\n' > "${temporary_state_file}"
  printf 'ACTIVE_BACKEND=%s\n' "${active_slot}" >> "${temporary_state_file}"
  printf 'BACKEND_A_TAG=%s\n' "${backend_a_tag}" >> "${temporary_state_file}"
  printf 'BACKEND_B_TAG=%s\n' "${backend_b_tag}" >> "${temporary_state_file}"
  printf 'DEPLOYMENT_INITIALIZED=%s\n' "${deployment_initialized}" >> "${temporary_state_file}"

  chmod 600 "${temporary_state_file}"
  mv -- "${temporary_state_file}" "${DEPLOYMENT_ENV_FILE}"
  temporary_state_file=""
}

write_active_upstream() {
  local slot="$1"

  umask 077
  temporary_upstream_file="$(mktemp "${NGINX_RUNTIME_DIR}/.active-backend.conf.XXXXXX")"

  printf '# Generated by deploy-backend.sh. Do not commit this file.\n' > "${temporary_upstream_file}"
  printf 'set $backend_upstream backend-%s:8080;\n' "${slot}" >> "${temporary_upstream_file}"

  chmod 644 "${temporary_upstream_file}"
  mv -- "${temporary_upstream_file}" "${ACTIVE_BACKEND_FILE}"
  temporary_upstream_file=""
}

read_deployment_state() {
  ACTIVE_BACKEND=""
  BACKEND_A_TAG=""
  BACKEND_B_TAG=""
  DEPLOYMENT_INITIALIZED=""

  while IFS='=' read -r key value; do
    case "${key}" in
      ACTIVE_BACKEND) ACTIVE_BACKEND="${value}" ;;
      BACKEND_A_TAG) BACKEND_A_TAG="${value}" ;;
      BACKEND_B_TAG) BACKEND_B_TAG="${value}" ;;
      DEPLOYMENT_INITIALIZED) DEPLOYMENT_INITIALIZED="${value}" ;;
    esac
  done < "${DEPLOYMENT_ENV_FILE}"

  if [[ "${ACTIVE_BACKEND}" != "a" && "${ACTIVE_BACKEND}" != "b" ]]; then
    fail "runtime/deployment.env contains an invalid ACTIVE_BACKEND value."
  fi

  is_valid_tag "${BACKEND_A_TAG}" || fail "runtime/deployment.env contains an invalid BACKEND_A_TAG."
  is_valid_tag "${BACKEND_B_TAG}" || fail "runtime/deployment.env contains an invalid BACKEND_B_TAG."

  if [[ "${DEPLOYMENT_INITIALIZED}" != "true" && "${DEPLOYMENT_INITIALIZED}" != "false" ]]; then
    fail "runtime/deployment.env contains an invalid DEPLOYMENT_INITIALIZED value."
  fi
}

verify_state_matches_upstream() {
  local expected_line
  expected_line="set \$backend_upstream backend-${ACTIVE_BACKEND}:8080;"

  grep -Fqx "${expected_line}" "${ACTIVE_BACKEND_FILE}" \
    || fail "deployment state and Nginx active upstream do not match."
}

wait_until_healthy() {
  local slot="$1"
  local service="backend-${slot}"
  local container_id
  local health_status
  local previous_health_status=""
  local deadline=$((SECONDS + 120))

  container_id="$(compose --profile "${slot}" ps --all --quiet "${service}")"
  [[ -n "${container_id}" ]] || return 1

  while (( SECONDS < deadline )); do
    health_status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "${container_id}")"

    # 같은 상태를 반복하지 않고 변화가 있을 때만 남겨 Actions에서 시작 흐름을 확인한다.
    if [[ "${health_status}" != "${previous_health_status}" ]]; then
      printf 'backend-%s health status: %s\n' "${slot}" "${health_status}"
      previous_health_status="${health_status}"
    fi

    case "${health_status}" in
      healthy) return 0 ;;
      unhealthy|exited|dead) return 1 ;;
    esac

    sleep 2
  done

  return 1
}

capture_slot_diagnostics() {
  local slot="$1"
  local service="backend-${slot}"
  local container_id=""
  local diagnostics_dir="${RUNTIME_DIR}/diagnostics"
  local application_log_file="${diagnostics_dir}/backend-last-failure.log"

  printf '\nBackend deployment diagnostics for %s:\n' "${service}" >&2
  compose --profile "${slot}" ps --all "${service}" >&2 || true

  # 종료 코드, OOM 여부와 curl 기반 Health Check 기록에는 애플리케이션 환경변수가 포함되지 않는다.
  if container_id="$(compose --profile "${slot}" ps --all --quiet "${service}" 2>/dev/null)" \
    && [[ -n "${container_id}" ]]; then
    docker inspect \
      --format 'state={{.State.Status}} health={{if .State.Health}}{{.State.Health.Status}}{{else}}not-configured{{end}} exitCode={{.State.ExitCode}} oomKilled={{.State.OOMKilled}}' \
      "${container_id}" >&2 || true

    docker inspect \
      --format '{{if .State.Health}}{{range .State.Health.Log}}{{println .End "exit=" .ExitCode .Output}}{{end}}{{end}}' \
      "${container_id}" >&2 || true
  fi

  # 전체 Spring 로그는 Actions에 노출하지 않고 EC2의 소유자 전용 파일에 마지막 실패분만 보존한다.
  umask 077
  mkdir -p -- "${diagnostics_dir}"
  chmod 700 "${diagnostics_dir}"
  compose --profile "${slot}" logs --no-color --tail=200 "${service}" \
    > "${application_log_file}" 2>&1 || true
  chmod 600 "${application_log_file}"

  printf 'Spring Boot logs were saved securely on EC2: %s\n\n' \
    "${application_log_file}" >&2
}

stop_and_remove_slot() {
  local slot="$1"
  local service="backend-${slot}"

  compose --profile "${slot}" stop "${service}" >/dev/null 2>&1 || true
  compose --profile "${slot}" rm --force "${service}" >/dev/null 2>&1 || true
}

test_nginx_proxy() {
  local attempt

  for attempt in {1..15}; do
    if compose exec -T frontend \
      wget -q -O /dev/null -T 5 http://127.0.0.1/api/actuator/health; then
      return 0
    fi

    sleep 2
  done

  return 1
}

rollback_upstream() {
  local previous_slot="$1"

  write_active_upstream "${previous_slot}"

  if ! compose exec -T frontend nginx -t; then
    warn "rollback Nginx configuration validation failed. Manual recovery is required."
    return 1
  fi

  if ! compose exec -T frontend nginx -s reload; then
    warn "rollback Nginx reload failed. Manual recovery is required."
    return 1
  fi
}

if [[ ! -e "${DEPLOYMENT_ENV_FILE}" && ! -e "${ACTIVE_BACKEND_FILE}" ]]; then
  # 첫 실행은 A를 활성 슬롯으로 정하되 smoke test 전까지 초기화 완료로 기록하지 않는다.
  write_deployment_state a "${new_backend_tag}" "${new_backend_tag}" false
  write_active_upstream a
elif [[ ! -f "${DEPLOYMENT_ENV_FILE}" || ! -f "${ACTIVE_BACKEND_FILE}" ]]; then
  fail "only part of the deployment runtime state exists. Restore or remove it before retrying."
fi

read_deployment_state
verify_state_matches_upstream

if [[ "${DEPLOYMENT_INITIALIZED}" == "false" ]]; then
  initial_deployment=true
  target_slot="a"
  previous_slot=""

  # 최초 배포 재시도에서는 전달받은 새 태그로 A/B 기준 이미지를 다시 맞춘다.
  BACKEND_A_TAG="${new_backend_tag}"
  BACKEND_B_TAG="${new_backend_tag}"
  write_deployment_state a "${BACKEND_A_TAG}" "${BACKEND_B_TAG}" false
  write_active_upstream a
else
  initial_deployment=false
  previous_slot="${ACTIVE_BACKEND}"

  if [[ "${ACTIVE_BACKEND}" == "a" ]]; then
    target_slot="b"
    BACKEND_B_TAG="${new_backend_tag}"
  else
    target_slot="a"
    BACKEND_A_TAG="${new_backend_tag}"
  fi

  # 비활성 슬롯이 새 이미지를 사용하도록 태그만 먼저 변경하며 활성 슬롯은 그대로 유지한다.
  write_deployment_state "${ACTIVE_BACKEND}" "${BACKEND_A_TAG}" "${BACKEND_B_TAG}" true
fi

target_service="backend-${target_slot}"

# 실제 컨테이너를 변경하기 전에 환경변수와 profile을 포함한 Compose 설정을 검증한다.
compose --profile "${target_slot}" config --quiet

printf 'Pulling backend image for slot %s...\n' "${target_slot}"
compose --profile "${target_slot}" pull "${target_service}"

if [[ "${initial_deployment}" == true ]]; then
  # 최초 전환에서는 external upstream 설정이 포함된 프론트 이미지도 함께 준비한다.
  compose --profile a pull frontend
fi

printf 'Starting backend slot %s...\n' "${target_slot}"
if ! compose --profile "${target_slot}" up -d --no-deps "${target_service}"; then
  capture_slot_diagnostics "${target_slot}"
  stop_and_remove_slot "${target_slot}"
  fail "failed to start backend-${target_slot}."
fi

if ! wait_until_healthy "${target_slot}"; then
  capture_slot_diagnostics "${target_slot}"
  stop_and_remove_slot "${target_slot}"
  fail "backend-${target_slot} exited, became unhealthy, or did not become healthy within 120 seconds."
fi

if [[ "${initial_deployment}" == true ]]; then
  printf 'Starting frontend with the A/B upstream mount...\n'

  if ! compose --profile a up -d --no-deps frontend; then
    stop_and_remove_slot a
    fail "failed to start the frontend with the A/B upstream configuration."
  fi

  compose exec -T frontend nginx -t \
    || fail "frontend Nginx configuration validation failed."

  test_nginx_proxy \
    || fail "frontend could not reach backend-a through /api/actuator/health."

  # 새 프론트와 A가 정상인 것을 확인한 뒤 기존 단일 backend 서비스를 orphan으로 제거한다.
  compose --profile a up -d --no-deps --remove-orphans frontend

  write_deployment_state a "${BACKEND_A_TAG}" "${BACKEND_B_TAG}" true

  printf 'Initial deployment completed. Frontend now routes to backend-a.\n'
  exit 0
fi

printf 'Switching Nginx from backend-%s to backend-%s...\n' "${previous_slot}" "${target_slot}"
write_active_upstream "${target_slot}"

if ! compose exec -T frontend nginx -t; then
  write_active_upstream "${previous_slot}"
  stop_and_remove_slot "${target_slot}"
  fail "new Nginx upstream configuration is invalid."
fi

if ! compose exec -T frontend nginx -s reload; then
  rollback_upstream "${previous_slot}" || true
  stop_and_remove_slot "${target_slot}"
  fail "Nginx reload failed."
fi

if ! test_nginx_proxy; then
  rollback_upstream "${previous_slot}" || true
  stop_and_remove_slot "${target_slot}"
  fail "smoke test failed after switching Nginx; the previous slot was restored."
fi

# 전환과 smoke test가 모두 성공한 뒤에만 새 슬롯을 활성 상태로 기록한다.
write_deployment_state "${target_slot}" "${BACKEND_A_TAG}" "${BACKEND_B_TAG}" true

if ! compose --profile "${previous_slot}" stop "backend-${previous_slot}"; then
  warn "the previous backend could not be stopped automatically. Check it manually."
else
  compose --profile "${previous_slot}" rm --force "backend-${previous_slot}" >/dev/null 2>&1 \
    || warn "the stopped previous backend container could not be removed automatically."
fi

printf 'Deployment completed successfully. Active backend: %s, image tag: %s\n' \
  "${target_slot}" "${new_backend_tag}"
